### ISSUE TITLE
Sketchybar dotfiles, icons problem

### ISSUE THREAD

**Issue by BR00l** [itaysharir/Dotfiles#2]
Hello there, I just installed your sketchybar dots, and I really liked it :) 
The only issue I have is that the icons are not displayed.
Do you have a clue why this happens?

![image](https://user-images.githubusercontent.com/454575/201362103-2da27409-c72e-4d48-8374-83b03419e635.png)

**Comment by itaysharir** [comment]
Sorry for the late reply, i forgot to check this repo for issues. You need to install the Ubuntu font and Fontawesome. If you have homebrew installed you can do it with: ```brew tap homebrew/cask-fonts && brew install font-ubuntu && brew install font-fontawesome``` I'll add these dependencies to README.md
